#  打包
# cp ecosystem.config.cjs
name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: pnpm/action-setup@v3.0.0
      - run: pnpm install
      - run: pnpm build
      - run: node .output/server/index.mjs
